// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZakasOne.DataConnection;

#nullable disable

namespace ZakasOne.Migrations
{
    [DbContext(typeof(ZakasData))]
    [Migration("20260210121031_one")]
    partial class one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZakasOne.Model.Zakas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Berilgan_vaqt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kocha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Massa")
                        .HasColumnType("integer");

                    b.Property<string>("Tuman")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uy_Manzili")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zakas");
                });
#pragma warning restore 612, 618
        }
    }
}
